package com.denser.june.core.presentation.theme

import androidx.compose.ui.graphics.Color


val PurpleLight_Primary = Color(0xFF6750A4)
val PurpleLight_OnPrimary = Color(0xFFFFFFFF)
val PurpleLight_PrimaryContainer = Color(0xFFE9DDFF)
val PurpleLight_OnPrimaryContainer = Color(0xFF22005D)
val PurpleLight_Secondary = Color(0xFF625B71)
val PurpleLight_OnSecondary = Color(0xFFFFFFFF)
val PurpleLight_SecondaryContainer = Color(0xFFE8DEF8)
val PurpleLight_OnSecondaryContainer = Color(0xFF1E192B)
val PurpleLight_Tertiary = Color(0xFF7E5260)
val PurpleLight_OnTertiary = Color(0xFFFFFFFF)
val PurpleLight_TertiaryContainer = Color(0xFFFFD9E3)
val PurpleLight_OnTertiaryContainer = Color(0xFF31101D)
val PurpleLight_Error = Color(0xFFBA1A1A)
val PurpleLight_Background = Color(0xFFFFFBFF)
val PurpleLight_Surface = Color(0xFFFFFBFF)


val PurpleDark_Primary = Color(0xFFCFBCFF)
val PurpleDark_OnPrimary = Color(0xFF381E72)
val PurpleDark_PrimaryContainer = Color(0xFF4F378A)
val PurpleDark_OnPrimaryContainer = Color(0xFFE9DDFF)
val PurpleDark_Secondary = Color(0xFFCBC2DB)
val PurpleDark_OnSecondary = Color(0xFF332D41)
val PurpleDark_SecondaryContainer = Color(0xFF4A4458)
val PurpleDark_OnSecondaryContainer = Color(0xFFE8DEF8)
val PurpleDark_Tertiary = Color(0xFFEFB8C8)
val PurpleDark_OnTertiary = Color(0xFF4A2532)
val PurpleDark_TertiaryContainer = Color(0xFF633B48)
val PurpleDark_OnTertiaryContainer = Color(0xFFFFD9E3)
val PurpleDark_Error = Color(0xFFFFB4AB)
val PurpleDark_Background = Color(0xFF1C1B1E)
val PurpleDark_Surface = Color(0xFF1C1B1E)


val BlueLight_Primary = Color(0xFF0061A4)
val BlueLight_OnPrimary = Color(0xFFFFFFFF)
val BlueLight_PrimaryContainer = Color(0xFFD1E4FF)
val BlueLight_OnPrimaryContainer = Color(0xFF001D36)
val BlueLight_Secondary = Color(0xFF535F70)
val BlueLight_OnSecondary = Color(0xFFFFFFFF)
val BlueLight_SecondaryContainer = Color(0xFFD7E3F7)
val BlueLight_OnSecondaryContainer = Color(0xFF101C2B)
val BlueLight_Tertiary = Color(0xFF6B5778)
val BlueLight_OnTertiary = Color(0xFFFFFFFF)
val BlueLight_TertiaryContainer = Color(0xFFF2DAFF)
val BlueLight_OnTertiaryContainer = Color(0xFF251431)
val BlueLight_Error = Color(0xFFBA1A1A)
val BlueLight_Background = Color(0xFFFDFCFF)
val BlueLight_Surface = Color(0xFFFDFCFF)


val BlueDark_Primary = Color(0xFF9ECAFF)
val BlueDark_OnPrimary = Color(0xFF003258)
val BlueDark_PrimaryContainer = Color(0xFF00497D)
val BlueDark_OnPrimaryContainer = Color(0xFFD1E4FF)
val BlueDark_Secondary = Color(0xFFBBC7DB)
val BlueDark_OnSecondary = Color(0xFF253140)
val BlueDark_SecondaryContainer = Color(0xFF3B4858)
val BlueDark_OnSecondaryContainer = Color(0xFFD7E3F7)
val BlueDark_Tertiary = Color(0xFFD6BEE4)
val BlueDark_OnTertiary = Color(0xFF3B2948)
val BlueDark_TertiaryContainer = Color(0xFF523F5F)
val BlueDark_OnTertiaryContainer = Color(0xFFF2DAFF)
val BlueDark_Error = Color(0xFFFFB4AB)
val BlueDark_Background = Color(0xFF1A1C1E)
val BlueDark_Surface = Color(0xFF1A1C1E)


val GreenLight_Primary = Color(0xFF006E1C)
val GreenLight_OnPrimary = Color(0xFFFFFFFF)
val GreenLight_PrimaryContainer = Color(0xFF96F990)
val GreenLight_OnPrimaryContainer = Color(0xFF002204)
val GreenLight_Secondary = Color(0xFF526350)
val GreenLight_OnSecondary = Color(0xFFFFFFFF)
val GreenLight_SecondaryContainer = Color(0xFFD5E8D0)
val GreenLight_OnSecondaryContainer = Color(0xFF101F10)
val GreenLight_Tertiary = Color(0xFF39656B)
val GreenLight_OnTertiary = Color(0xFFFFFFFF)
val GreenLight_TertiaryContainer = Color(0xFFBCEBF2)
val GreenLight_OnTertiaryContainer = Color(0xFF001F24)
val GreenLight_Error = Color(0xFFBA1A1A)
val GreenLight_Background = Color(0xFFFCFDF7)
val GreenLight_Surface = Color(0xFFFCFDF7)


val GreenDark_Primary = Color(0xFF7ADC76)
val GreenDark_OnPrimary = Color(0xFF00390A)
val GreenDark_PrimaryContainer = Color(0xFF005313)
val GreenDark_OnPrimaryContainer = Color(0xFF96F990)
val GreenDark_Secondary = Color(0xFFB9CCB5)
val GreenDark_OnSecondary = Color(0xFF243424)
val GreenDark_SecondaryContainer = Color(0xFF3A4B39)
val GreenDark_OnSecondaryContainer = Color(0xFFD5E8D0)
val GreenDark_Tertiary = Color(0xFFA1CED5)
val GreenDark_OnTertiary = Color(0xFF00363D)
val GreenDark_TertiaryContainer = Color(0xFF1F4D53)
val GreenDark_OnTertiaryContainer = Color(0xFFBCEBF2)
val GreenDark_Error = Color(0xFFFFB4AB)
val GreenDark_Background = Color(0xFF1A1C19)
val GreenDark_Surface = Color(0xFF1A1C19)


val OrangeLight_Primary = Color(0xFF8B5000)
val OrangeLight_OnPrimary = Color(0xFFFFFFFF)
val OrangeLight_PrimaryContainer = Color(0xFFFFDDB5)
val OrangeLight_OnPrimaryContainer = Color(0xFF2C1700)
val OrangeLight_Secondary = Color(0xFF6F5B40)
val OrangeLight_OnSecondary = Color(0xFFFFFFFF)
val OrangeLight_SecondaryContainer = Color(0xFFFADEBC)
val OrangeLight_OnSecondaryContainer = Color(0xFF271904)
val OrangeLight_Tertiary = Color(0xFF516440)
val OrangeLight_OnTertiary = Color(0xFFFFFFFF)
val OrangeLight_TertiaryContainer = Color(0xFFD3EABC)
val OrangeLight_OnTertiaryContainer = Color(0xFF102004)
val OrangeLight_Error = Color(0xFFBA1A1A)
val OrangeLight_Background = Color(0xFFFFFBFF)
val OrangeLight_Surface = Color(0xFFFFFBFF)


val OrangeDark_Primary = Color(0xFFFFB95E)
val OrangeDark_OnPrimary = Color(0xFF4A2800)
val OrangeDark_PrimaryContainer = Color(0xFF6A3C00)
val OrangeDark_OnPrimaryContainer = Color(0xFFFFDDB5)
val OrangeDark_Secondary = Color(0xFFDDC3A2)
val OrangeDark_OnSecondary = Color(0xFF3E2E16)
val OrangeDark_SecondaryContainer = Color(0xFF56442B)
val OrangeDark_OnSecondaryContainer = Color(0xFFFADEBC)
val OrangeDark_Tertiary = Color(0xFFB7CEA1)
val OrangeDark_OnTertiary = Color(0xFF243516)
val OrangeDark_TertiaryContainer = Color(0xFF3A4C2B)
val OrangeDark_OnTertiaryContainer = Color(0xFFD3EABC)
val OrangeDark_Error = Color(0xFFFFB4AB)
val OrangeDark_Background = Color(0xFF201B16)
val OrangeDark_Surface = Color(0xFF201B16)


val RoseLight_Primary = Color(0xFF99405F)
val RoseLight_OnPrimary = Color(0xFFFFFFFF)
val RoseLight_PrimaryContainer = Color(0xFFFFD9E2)
val RoseLight_OnPrimaryContainer = Color(0xFF3E001D)
val RoseLight_Secondary = Color(0xFF75565D)
val RoseLight_OnSecondary = Color(0xFFFFFFFF)
val RoseLight_SecondaryContainer = Color(0xFFFFD9E0)
val RoseLight_OnSecondaryContainer = Color(0xFF2B151B)
val RoseLight_Tertiary = Color(0xFF7C5635)
val RoseLight_OnTertiary = Color(0xFFFFFFFF)
val RoseLight_TertiaryContainer = Color(0xFFFFDCC1)
val RoseLight_OnTertiaryContainer = Color(0xFF2E1500)
val RoseLight_Error = Color(0xFFBA1A1A)
val RoseLight_Background = Color(0xFFFFFBFF)
val RoseLight_Surface = Color(0xFFFFFBFF)


val RoseDark_Primary = Color(0xFFFFB1C8)
val RoseDark_OnPrimary = Color(0xFF5E1133)
val RoseDark_PrimaryContainer = Color(0xFF7B2947)
val RoseDark_OnPrimaryContainer = Color(0xFFFFD9E2)
val RoseDark_Secondary = Color(0xFFE3BDC6)
val RoseDark_OnSecondary = Color(0xFF422930)
val RoseDark_SecondaryContainer = Color(0xFF5A3F46)
val RoseDark_OnSecondaryContainer = Color(0xFFFFD9E0)
val RoseDark_Tertiary = Color(0xFFEFBD94)
val RoseDark_OnTertiary = Color(0xFF48290C)
val RoseDark_TertiaryContainer = Color(0xFF623F20)
val RoseDark_OnTertiaryContainer = Color(0xFFFFDCC1)
val RoseDark_Error = Color(0xFFFFB4AB)
val RoseDark_Background = Color(0xFF201A1B)
val RoseDark_Surface = Color(0xFF201A1B)